image: maven:3-jdk-8

build:
  script:
    - cd java/riorita
    - mvn validate --batch-mode
    - mvn -Dfile.encoding=UTF-8 -DcreateChecksum=true clean source:jar javadoc:jar repository:bundle-create install --batch-mode
